### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by nincao** [weilsonwonder/WWCalendarTimeSelector#5] opened 2016-07-27 04:54 UTC
Class: WWCalendarTimeSelector.swift

**"Line 606: let picker = UIStoryboard(name: "WWCalendarTimeSelector", bundle: bundle).instantiateInitialViewController() as! WWCalendarTimeSelector"**

Note that when the project does not have the same name "Executable file" generates error. I changed like this in the attached image and resolved the error line 606. But spawned another error.  I changed **"Custom Class"** the **"Module"** field to the name of the current project.

![screen shot 2016-07-27 at 01 45 05](https://cloud.githubusercontent.com/assets/1202857/17164153/cbca88f0-539b-11e6-9a15-22bd30dfec22.png)

and new error

Generates error from this point.
**Line 671: clockView.delegate = self**
![screen shot 2016-07-27 at 01 50 45](https://cloud.githubusercontent.com/assets/1202857/17164230/9383fd0e-539c-11e6-8dc9-e9ec5c8022fe.png)

**Comment by weilsonwonder** [comment] 2016-08-04 02:04
Hi, have you tried to do this instead? 

// 1. You must instantiate with the class function instantiate()
let selector = WWCalendarTimeSelector.instantiate()

**Comment by ajijoyo** [comment] 2016-08-05 10:33
hello,
I got same issue, 
i manually drag 'source' files to my projects, and check copy item if needed
i change module to my project and get same error
and yes, i added 'WWCalendarTimeSelector.instantiate()'
did i get wrong import files or something?
<img width="488" alt="screen shot 2016-08-05 at 5 27 54 pm" src="https://cloud.githubusercontent.com/assets/10805529/17433979/f894e932-5b31-11e6-8ac3-5bea82f1278c.png">

**Comment by weilsonwonder** [comment] 2016-08-05 13:47
Hi, I'm not entirely sure why this happens as I'm relatively new to creating libraries, and I'm not entirely sure how it works when you drag and drop source codes from libraries like mine. 

Anyone from the community could assist in resolving this? (:

**Comment by ajijoyo** [comment] 2016-08-05 16:14
hello i found the problem is,
first get ClockView on storyboard
<img width="403" alt="screen shot 2016-08-05 at 23 11 07" src="https://cloud.githubusercontent.com/assets/10805529/17442876/0dd7a610-5b62-11e6-8b3d-293b4fee2176.png">

second you can remove moduls on that view(im not sure about remove this moduls, but its work 😄  )
<img width="250" alt="screen shot 2016-08-05 at 23 11 14" src="https://cloud.githubusercontent.com/assets/10805529/17442890/1b81a48c-5b62-11e6-9c5a-088d267f22e1.png">

**Comment by nincao** [comment] 2016-08-05 18:11
Ajijoyo thanks a lot, parabens obrigado.

**Closed** 2016-08-08 02:42 UTC
